version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./:/app
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A DjangoProjectHillel worker -l INFO -B'
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq
  db:
    platform: linux/x86_64
    image: mysql:8.0.21
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
  cache:
    image: memcached
    ports:
      - '11211:11211'
    restart: on-failure
    depends_on:
      - app

