# Generated by Django 4.1.1 on 2022-10-04 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('limited_integer_field', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('limited_integer_field', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
