# Generated by Django 4.1.1 on 2022-10-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='limited_integer_field',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='limited_integer_field',
            new_name='age',
        ),
    ]
