# Generated by Django 4.1.1 on 2022-10-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
