# Generated by Django 4.1.1 on 2022-10-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_category_remove_course_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
