# Generated by Django 4.1.1 on 2022-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thesis',
            field=models.TextField(blank=True),
        ),
    ]
