# Generated by Django 4.1.1 on 2022-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thesis',
            field=models.CharField(max_length=255),
        ),
    ]
