# Generated by Django 4.1.1 on 2022-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
