# Generated by Django 4.1.1 on 2022-10-13 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(18)]),
        ),
    ]
