# Generated by Django 4.1.3 on 2022-11-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_student_email_delayedmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
